sudo: false

language: node_js

node_js:
  - "6.11.0"
  - "7"
  - "5"
  - "4"

before_install:
 - npm install -g npm@">=5.0.0"
 - npm --version

notifications:
  disabled: true

env:
  - CXX=g++-6

cache:
  directories:
    - "node_modules"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6